# Generated by Django 2.0.1 on 2018-01-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0006_auto_20180124_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
